# Generated by Django 3.1.3 on 2021-01-14 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='fetched_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 23, 30, 59, 420330)),
        ),
    ]
