# Generated by Django 3.1.3 on 2021-01-14 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_fetched_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='fetched_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 23, 33, 30, 187544)),
        ),
    ]
