# Generated by Django 3.1.3 on 2021-01-14 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210114_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='fetched_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
