# Generated by Django 3.1.3 on 2021-01-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210114_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
