# Generated by Django 3.1.3 on 2021-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_true',
            field=models.BooleanField(default=True),
        ),
    ]
