# Generated by Django 3.1.3 on 2021-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210115_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='is_real',
            field=models.CharField(default='REAL', max_length=255),
        ),
    ]
